---
server:
    install: '1'
    timezone: UTC
    locale: fr_FR.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: default, ip: 192.168.33.99, memory: '512', sharedfolder: ./, useVagrantCloud: '1', syncType: nfs }
nginx:
    install: '1'
    docroot: /vagrant
    servername: coding-dojo.dev
php:
    install: '1'
    ppa: php
    packages: [php5-cli, php5-intl, php5-mcrypt, php5-mysql]
composer:
    install: '1'

